### ISSUE TITLE
Hosted for all people :) 

### ISSUE THREAD

**Issue by Penguinehis** [dom111/image-to-ansi#3]
Here I hosted in my dedicated for everyone to use, kept your credits and github link, your work is amazing and saved me a lot of headaches with my scripts

https://xeon.worldofdragon.net:8443/sisu/ - Image to ANSI

https://xeon.worldofdragon.net:8443/sisu2/ - Gif to ANSI

**Comment by dom111** [comment]
Thanks @Penguinehis, glad you like it!

These are also on dom111.github.io/image-to-ansi and dom111.github.io/gif-to-ansi!

Recently updated both of these to make them a little more efficient, using xterm.js!
